//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDeffenderWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sound
    {
        public int SoundID { get; set; }
        public string SoundName { get; set; }
        public string Link { get; set; }
        public Nullable<System.TimeSpan> Length { get; set; }
        public string Language { get; set; }
        public string FileType { get; set; }
        public Nullable<short> Version { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
