//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDeffenderWebAPIMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string MovieLink { get; set; }
        public string LinkType { get; set; }
        public string Language { get; set; }
        public string MovieNameEnglish { get; set; }
        public Nullable<int> FavID { get; set; }
        public Nullable<bool> IsContinueable { get; set; }
        public Nullable<bool> NextID { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> MinAge { get; set; }
        public Nullable<int> ManyViews { get; set; }
        public Nullable<System.DateTime> DateLastView { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string new_tablecol { get; set; }
    }
}
