//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDeffenderWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChildrenDeffenderEntities1 : DbContext
    {
        public ChildrenDeffenderEntities1()
            : base("name=ChildrenDeffenderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<IndexImage> IndexImage { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Sound> Sound { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
