//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDeffenderForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexImage
    {
        public int IndexImageID { get; set; }
        public string IndexImageName { get; set; }
        public string Type { get; set; }
        public Nullable<short> SizeX { get; set; }
        public Nullable<short> SizeY { get; set; }
        public Nullable<bool> IsTransparency { get; set; }
        public Nullable<short> Version { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
